name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t your-dockerhub-username/your-image-name:latest .

      - name: Publish Docker Image
        run: docker push your-dockerhub-username/your-image-name:latest
