name: Docker Build and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get last 8 digits of commit hash
        id: get_hash
        run: |
          hash=$(git rev-parse --short=8 HEAD)
          echo "Last 8 digits of commit hash: $hash"
          echo "::set-output name=hash::$hash"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Linux Docker Image
        run: docker build -f Dockerfile.linux -t ${{ secrets.DOCKER_USERNAME }}/api-demo-linux:${{ steps.get_hash.outputs.hash }} .

      - name: Publish Linux Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/api-demo-linux:${{ steps.get_hash.outputs.hash }}

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get last 8 digits of commit hash
        id: get_hash
        run: |
          $hash = (git rev-parse --short=8 HEAD)
          Write-Output "Last 8 digits of commit hash: $hash"
          echo "::set-output name=hash::$hash"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Windows Docker Image
        run: docker build -f Dockerfile.windows -t ${{ secrets.DOCKER_USERNAME }}/api-demo-windows:${{ steps.get_hash.outputs.hash }} .

      - name: Publish Windows Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/api-demo-windows:${{ steps.get_hash.outputs.hash }}
